### ISSUE TITLE
basic chosen IO C modules usable from NIM

### ISSUE THREAD

**Issue by despiegk** [nimscale/home#1]
usable means
- nice examples
- documentation
- installable through nimble on ubuntu 16.04

chosen modules
- intel ISA = encryption, crc, erasure coding: see issues there for requirements
- [Buse](https://github.com/nimscale/buse) is like fuse but for vol driver
- [fuse](https://github.com/nimscale/fuse) there is code but need much better examples

**Comment by nbabenko** [comment]
not actual, closing the issue
